name: Release

on:
  workflow_dispatch:
  push:
    tags: '1.6.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: antville

    env:
      GH_TOKEN: ${{ github.token }}
      LC_TIME: en_US.UTF-8

    steps:
      - uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew assembleDist

      - name: Create release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          url: https://code.host.antville.org
          token: ${{ github.token }}
          title: Antville ${{ github.ref_name }}
          release-dir: build/distributions
          release-notes-assistant: true
          verbose: true
