name: Deploy (Staging)

on: 
  workflow_dispatch:
    inputs:
      hostname:
        description: Hostname
        type: string
        required: true
        default: antville.org

jobs:
  stage:
    runs-on: antville

    environment:
      name: stage
      url: ${{ inputs.hostname }}

    steps:
      - uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew :build

      - name: Copy files to server
        # The rsync command applies the same filters as the one in tools/extras/deploy.sh
        run: |
          rsync ./build/install/antville/ ${{ inputs.hostname }}:./apps/antville/ \
            --archive --compress --delete --verbose \
            --filter '+ /claustra' \
            --filter '+ /code' \
            --filter '+ /compat' \
            --filter '+ /db' \
            --filter '+ /i18n' \
            --filter '+ /lib' \
            --filter '- /*'
          rsync ./build/install/antville/static/ ${{ inputs.hostname }}:./apps/antville/static/ \
            --archive --compress --verbose \
            --filter '+ /fonts' \
            --filter '+ /formica.html' \
            --filter '+ /img' \
            --filter '+ /scripts' \
            --filter '+ /styles' \
            --filter '- /*'

      - name: Restart Helma
        run: ssh ${{ inputs.hostname }} restart

