name: Deploy (Staging)

on: workflow_dispatch

jobs:
  stage:
    runs-on: ubuntu-latest

    environment:
      name: stage
      url: https://antville-test.click

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: antville/helma/.github/actions/ssh@helma-🐜
        with:
          config: ${{ vars.SSH_CONFIG }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew :build

      - name: Publish to staging server
        # The rsync command applies the same filters as the one in tools/extras/deploy.sh
        run: |
          rsync ./build/install/antville/ staging-server:./apps/antville/ \
            --archive --compress --delete --verbose \
            --filter '+ /claustra' \
            --filter '+ /code' \
            --filter '+ /compat' \
            --filter '+ /db' \
            --filter '+ /i18n' \
            --filter '+ /lib' \
            --filter '- /*'
          rsync ./build/install/antville/static/ staging-server:./apps/antville/static/ \
            --archive --compress --verbose \
            --filter '+ /fonts' \
            --filter '+ /formica.html' \
            --filter '+ /img' \
            --filter '+ /scripts' \
            --filter '+ /styles' \
            --filter '- /*'

      - name: Restart Helma
        run: ssh staging-server restart

