name: Deploy (Staging)

on:
  workflow_dispatch

env:
  SSH_AUTH_SOCK: /tmp/ssh-agent.sock

jobs:
  stage:
    runs-on: ubuntu-latest

    environment:
      name: stage
      url: https://antville-test.click

    steps:
      - uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew :build

      - name: Set up SSH agent
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          mkdir -p ~/.ssh
          echo '${{ vars.SSH_CONFIG }}' > ~/.ssh/config
          echo '${{ vars.KNOWN_HOSTS }}' > ~/.ssh/known_hosts

      - name: Publish to staging server
        # The rsync command applies the same filters as the one in tools/extras/deploy.sh
        run: |
          rsync ./build/install/antville/ antville.dev:./apps/antville/ \
            --archive --compress --delete --verbose \
            --filter '+ /claustra' \
            --filter '+ /code' \
            --filter '+ /compat' \
            --filter '+ /i18n' \
            --filter '+ /lib' \
            --filter '- /*'
          rsync ./build/install/antville/static/ antville.dev:./apps/antville/static/helma/ \
            --archive --compress --delete --verbose \
            --filter '+ /fonts' \
            --filter '+ /formica.html' \
            --filter '+ /img' \
            --filter '+ /scripts' \
            --filter '+ /styles' \
            --filter '- /*'

      - name: Restart Helma
        run: ssh antville.dev restart

