name: Deploy (Staging)

on: workflow_dispatch

jobs:
  stage:
    runs-on: antville

    environment:
      name: stage
      url: ${{ vars.stage_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew :build

      - name: Publish to staging server
        # The rsync command applies the same filters as the one in tools/extras/deploy.sh
        run: |
          rsync ./build/install/antville/ staging-server:./apps/antville/ \
            --archive --compress --delete --verbose \
            --filter '+ /claustra' \
            --filter '+ /code' \
            --filter '+ /compat' \
            --filter '+ /db' \
            --filter '+ /i18n' \
            --filter '+ /lib' \
            --filter '- /*'
          rsync ./build/install/antville/static/ staging-server:./apps/antville/static/ \
            --archive --compress --verbose \
            --filter '+ /fonts' \
            --filter '+ /formica.html' \
            --filter '+ /img' \
            --filter '+ /scripts' \
            --filter '+ /styles' \
            --filter '- /*'

      - name: Restart Helma
        run: ssh staging-server restart

